[package]
name = "egui_logger"
version = "0.5.0"
edition = "2021"
authors = ["Jacob <RegenJacob@gmx.de>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/RegenJacob/egui_logger"
description = "log implementation for egui"
categories = ["gui", "game-development", "development-tools::debugging"]
include = ["src/*.rs", "Cargo.toml", "LICENSE"]

[dependencies]
log = "0.4"
egui = "0.29.0"
regex = "1.10"

[dev-dependencies]
eframe = "0.29.0"
multi_log = "0.1"
env_logger = "0.11"

